In [75]:
import numpy as np
import pandas as pd
import copy 

In [76]:
# 自定义数据类型
t = np.dtype([('name', str, 40), ("numitems", int), ("price", float)])
t


dtype([('name', '<U40'), ('numitems', '<i4'), ('price', '<f8')])

In [77]:
t['name']


dtype('<U40')

In [78]:
# 利用自定义数据类型定义数组
itemz = np.array([('Bread', 42, 3.14), ('milk', 13, 2.72)])


In [79]:
itemz[0]


array(['Bread', '42', '3.14'], dtype='<U32')

In [80]:
# 数组属性
a = np.array([[1, 2], [3, 4]])


In [81]:
# 数组形状
a.shape


(2, 2)

In [82]:
# 数据类型
a.dtype


dtype('int32')

In [83]:
# 数组维度
a.ndim


2

In [84]:
# 数组元素总个数
a.size


4

In [85]:
np.arange(2, 10, 2)


array([2, 4, 6, 8])

In [86]:
np.linspace(1, 20, 6)


array([ 1. ,  4.8,  8.6, 12.4, 16.2, 20. ])

In [87]:
np.logspace(1, 4, 2, base=2)


array([ 2., 16.])

In [88]:
np.zeros((2, 3), dtype=np.int32)


array([[0, 0, 0],
       [0, 0, 0]])

In [89]:
np.ones((2, 3), dtype=np.int32)


array([[1, 1, 1],
       [1, 1, 1]])

In [90]:
np.full((2, 3), 5)


array([[5, 5, 5],
       [5, 5, 5]])

In [91]:
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [92]:
x = np.array([
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8]
])
np.diag(x)


array([0, 4, 8])

In [93]:
np.diag(x, k=1)


array([1, 5])

In [94]:
np.diag(x, k=-1)


array([3, 7])

In [95]:
for i in range(5):
    np.random.seed(10)
    perm = np.random.permutation(10)
    print(perm)


[8 2 5 6 3 1 0 7 4 9]
[8 2 5 6 3 1 0 7 4 9]
[8 2 5 6 3 1 0 7 4 9]
[8 2 5 6 3 1 0 7 4 9]
[8 2 5 6 3 1 0 7 4 9]


In [96]:
b= np.arange(24).reshape(2,3,4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [97]:
b.size

24

In [98]:
# ===========组合==========

In [99]:
a = np.arange(9).reshape(3, 3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [100]:
b = 2*a
b


array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [101]:
# 水平组合
np.hstack((a,b))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [102]:
np.concatenate((a, b), axis=1)


array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [103]:
# 垂直组合
np.vstack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [104]:
np.concatenate((a, b), axis=0)


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [105]:
# 列组合，对于二维数组，column_stack和hstack的效果是相同的
np.column_stack((a,b))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [106]:
np.column_stack((a,b))==np.hstack((a,b))

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [107]:
# 行组合：对于二维数组，row_stack与vstack的效果是相同的
np.row_stack((a, b))


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [108]:
np.row_stack((a,b))==np.vstack((a,b))

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [109]:
### 分割

In [110]:
### 水平分割

In [111]:
a = np.arange(9).reshape((3, 3))
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [112]:
# 水平分割：沿着水平方向分割为3个相同大小的子数组
np.hsplit(a, 3)


[array([[0],
        [3],
        [6]]),
 array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]])]

In [113]:
# 调用split函数并在参数中指定参数axis=1
# np.array_split(a,3,axis=1)
np.array_split(a,3,axis=1)

[array([[0],
        [3],
        [6]]),
 array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]])]

In [114]:
# 垂直分割
np.vsplit(a,3)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [115]:
np.split(a,3,axis=0)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [116]:
# 读取文件
"""
def loadtxt(fname, dtype=float, comments='#', delimiter=None,
            converters=None, skiprows=0, usecols=None, unpack=False,
            ndmin=0, encoding='bytes', max_rows=None, *, like=None)
"""
...


Ellipsis

In [117]:
from io import StringIO   # StringIO behaves like a file object

In [118]:
d = StringIO("""A B C
1,2,3
#AA AAA
4,5,6
7,8,9""")


In [119]:
a, b = np.loadtxt(d, dtype=int, skiprows=1, comments="#",
                  delimiter=",", usecols=(0, 2), unpack=True)
a, b


(array([1, 4, 7]), array([3, 6, 9]))

In [120]:
# 保存文件
"""
def savetxt(fname, X, fmt='%.18e', delimiter=' ', newline='\n', header='',
            footer='', comments='# ', encoding=None)
"""
...

Ellipsis

In [121]:
i2 = np.eye(2)
i2


array([[1., 0.],
       [0., 1.]])

In [122]:
# 写入txt文件
np.savetxt("eye_i2.txt", i2, fmt="%d", delimiter=" ")

# eye_i2.txt:
# 1 0
# 0 1


In [123]:
# 统计函数
# 求和
# 均值，中位数，标准差，方差
# 最大值，最小值

In [124]:
# 排序函数
# sort()：排序
# argsort()：返回排序后的索引

In [125]:
np.random.seed(20)  # 设置随机种子
arr = np.random.randint(1,10,size=10)
arr

array([4, 5, 7, 8, 3, 1, 7, 9, 6, 4])

In [126]:
arr.sort()  # 直接排序
arr

array([1, 3, 4, 4, 5, 6, 7, 7, 8, 9])

In [140]:
arr = np.random.randint(1,10,size=(3,3))
arr

array([[7, 2, 9],
       [2, 1, 9],
       [6, 1, 7]])

In [143]:
# 安列排序
arr.sort(axis=1)
arr

array([[2, 7, 9],
       [1, 2, 9],
       [1, 6, 7]])

In [144]:
# 按行排序
arr.sort(axis=0)
arr

array([[1, 2, 7],
       [1, 6, 9],
       [2, 7, 9]])

In [145]:
arr = np.array([2,3,6,8,0,7])
arr

array([2, 3, 6, 8, 0, 7])

In [146]:
arr.argsort()

array([4, 0, 1, 2, 5, 3], dtype=int64)

In [147]:
# 去重与重复

In [148]:
mat = np.array([
    [1, 2],
    [3, 4]
])
mat

array([[1, 2],
       [3, 4]])

In [153]:
# 做重复
np.tile(mat, (1, 4))


array([[1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4]])

In [154]:
np.tile(mat, (3, 1))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [155]:
np.tile(mat, (3, 2))

array([[1, 2, 1, 2],
       [3, 4, 3, 4],
       [1, 2, 1, 2],
       [3, 4, 3, 4],
       [1, 2, 1, 2],
       [3, 4, 3, 4]])

In [156]:
# 去重

In [160]:
a=np.array([1,2,4,5,2,1,4,5,2,3])
a

array([1, 2, 4, 5, 2, 1, 4, 5, 2, 3])

In [161]:
np.unique(a)

array([1, 2, 3, 4, 5])

In [162]:
# 返回去重后的索引
np.unique(a,return_index=True)

(array([1, 2, 3, 4, 5]), array([0, 1, 9, 2, 3], dtype=int64))

In [163]:
# ufunc函数>>>通用函数
# --数字四则运算
# --数组比较运算
# --逻辑运算